const data = `SHRI AGAM PRAKASHAN TRUST	UNITED STATES OF AMERICA
SHRI AMBA SPORTS CARES INC.	UNITED STATES OF AMERICA
SHRI CHINTAMANI PARSHWNATH BHAGWAN	UNITED STATES OF AMERICA
SHRI FEDRA. ASSO. IN NORTH AMERICA	UNITED STATES OF AMERICA
SHRI INC. JAIN SOCIETY OF GREATER DETROIT	UNITED STATES OF AMERICA
SHRI JAIN CENTER OF NEW JERSEY	UNITED STATES OF AMERICA
SHRI JAIN CENTER OF NORTHERN CALIFORNIA	UNITED STATES OF AMERICA
SHRI JAIN CENTRE OF AMERICA-NEW YORK	UNITED STATES OF AMERICA
SHRI JAIN CENTRE OF NEW JERSEY	UNITED STATES OF AMERICA
SHRI JAIN CENTRE OF SOTHERN CALIFORNIA	UNITED STATES OF AMERICA
SHRI JAIN SAMAJ - EUROPE	U.K.
SHRI JAIN SANGH EAST LONDON ESSEX	U.K.
SHRI JAIN SANGH OF CHERRY HILL	UNITED STATES OF AMERICA
SHRI JAIN SOCIETY OF GREATER CLEVELAND	UNITED STATES OF AMERICA
SHRI JAIN SOCIETY OF GRETER DETROIT	UNITED STATES OF AMERICA
SHRI JAIN SOCIETY OF METRO. WASHINGTON	UNITED STATES OF AMERICA
SHRI JAIN SOCIETY OF MIDDLE TEN NESSEE	UNITED STATES OF AMERICA
SHRI JAIN SOCIETY OF PITTSBURGH	UNITED STATES OF AMERICA
SHRI JAIN SOCIETY OF TORRENTO	UNITED STATES OF AMERICA
SHRI JIAN SOCIETY OF PITTSBURGH	UNITED STATES OF AMERICA
SHRI MAHAVIR FOUNDATION	U.K.
SHRI NAVNAT VANIK ASSOCIATION OF UK	U.K.
SHRI OSHWAL CENTRE	U.K.
SHRI PARMANAND VIJAY POONAI CHARITABLE FOUNDATION INC.	UNITED STATES OF AMERICA
SHRI SV TEMPLE	UNITED STATES OF AMERICA
SHRI THE JAIN SANGH INC.	UNITED STATES OF AMERICA
SHRI THE JAIN SOCIETY OF METRO. CHICAGO	UNITED STATES OF AMERICA
SHRI VEETRAG KALYAN KENTRA CORPO.	UNITED STATES OF AMERICA`;




const udata = data.split('\n');

const obj = udata.map(obj1 => {
    const pair = obj1.split('\t');
    return {
        Name : pair[0],
        Location : pair[1]
    }
})

console.log(JSON.stringify(obj))